### ISSUE TITLE
Relate to the upgrade

### ISSUE THREAD

**Issue by Oyunaa** [ihsn/nada#17]
Hello, 
Our NADA version is 4.1. Is it possible to upgrade 4.1 to 4.5 directly? Because we already changed own custom design. Here is to link: http://web.nso.mn/nada

**Comment by mah0001** [comment]
Yes, you can upgrade. Please download the latest NADA 5.0.4 and run all the database migrations scripts to make sure the database is upgraded. You will need to run:

* https://nada.readthedocs.io/en/v5.0/upgrade-from-4.x-to-4.2.html
* https://nada.readthedocs.io/en/v5.0/upgrade-from-4.2-to-4.3.html
* https://nada.readthedocs.io/en/v5.0/upgrade-from-4.4-to-5.html

For your design changes, NADA now uses Bootstrap (https://getbootstrap.com/) and you will need to redo your changes. 

Please let me know if you need help with the migration/custom design and I can try to setup a Webex or Skype call.
