### ISSUE TITLE
Current status of version 5

### ISSUE THREAD

**Issue by glefebvr1** [ihsn/nada#2]
Hello,
I noticed that the ihsn.org still propose version 4.4 for download. Does it mean that the version 5 is not yet considered as production-ready ?
If so, when do you think that version 5 will be released for production ? In one month, six months, ... ?
Thanks in advance for your answer,
Best

**Comment by mah0001** [comment]
Hi

Thank you for contacting us. Our website is being updated, the NADA 5 is
the latest stable version. If you are planning to use nada, please download
the master branch or use the releases page on our GitHub repo.

Best
Mehmood

**Comment by glefebvr1** [comment]
Thanks a lot for your answer & for the website update !
