### ISSUE TITLE
Error adding a study

### ISSUE THREAD

**Issue by TauM-ops** [ihsn/nada#21]
Installed 5.0.5, I get an error when I add new study after selecting DDI file & RDF file and then click submit.
I get an error which says:
This page isn't working.
Server is currently unable to handle this request.
HTTP ERROR 500

**Comment by mah0001** [comment]
Enable the error logging feature in NADA by going to application/config/config.php file and look for the setting 'log_threshold' and set it to 1, save the config file and try uploading the DDI again. 

To see the error logs, look inside the 'logs' folder. The logs should have the error details. If you see no logs being created, please make sure the logs folder has both read/write permissions set.

If this does not solve the issue, please provide info about your environment. e.g. Windows or Linux. Apache or IIS?

**Comment by TauM-ops** [comment]
Thank you. Environment is as follows Linux and Apache.
Yes the Logs now have error details. This is the error that is coming up.
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
ERROR - 2020-02-27 06:20:31 --> Severity: error --> Exception: Call to undefined function JsonSchema\Uri\json_decode() /var/www/html/vendor/justinrainbow/json schema/src/JsonSchema/Uri/UriRetriever.php 210

**Comment by TauM-ops** [comment]
This has been resolved by enabling JSON support .
