### ISSUE TITLE
probleme with sqlsrv

### ISSUE THREAD

**Issue by hatemsedghiani** [ihsn/nada#22]
hi mahmood,

I have installed nada 5.0.4 with sql server, but i have a problem in nada/index.php/home, bellow the error

**An uncaught Exception was encountered
Type: Error

Message: Call to a member function row_array() on boolean

Filename: C:\wamp64\www\nada-master\application\models\Stats_model.php

Line Number: 64

Backtrace:

File: C:\wamp64\www\nada-master\application\views\static\home.php
Line: 3
Function: get_survey_count

File: C:\wamp64\www\nada-master\application\controllers\Page.php
Line: 185
Function: view

File: C:\wamp64\www\nada-master\application\controllers\Page.php
Line: 71
Function: static_page

File: C:\wamp64\www\nada-master\index.php
Line: 343
Function: require_once**

this url works fine when using database mysql

thank you

**Comment by hatemsedghiani** [comment]
the problem is the table surveys is not created in the sqlserver database, also the script create table survey in schema.sqlsrv.sql is different then mysql

**Comment by mah0001** [comment]
Can you please use the NADA 5.0.5 release? Are you installing as new instance or trying to upgrade an older version?

**Comment by hatemsedghiani** [comment]
ok
i try to install new instance
thank you

**Comment by hatemsedghiani** [comment]
hi
i installed 5.0.5 as new instance on sql server. but i have the same error and the table surveys is not created in the database
thank you

**Comment by mah0001** [comment]
Can we try Skype or Webex? It is hard to guess what's happening without looking at your environment. I am not sure if I have your correct email address, please send me a message on my gmail address.

**Comment by mah0001** [comment]
thanks @hatemsedghiani for helping debug the issue. The installation script for Microsoft SQL server is updated and available in the `develop` branch, see commit 692dc37.
