### ISSUE TITLE
Generating PDF with over 4000 variables timeout

### ISSUE THREAD

**Issue by t3chbg** [ihsn/nada#24]
Hi Mehmood - We have nested study publication with four data files and unable to generate the Metadata in PDF - It seems to timeout. Are there any limitations with publishing study with over 4k variables?

Incidentally, we see this behaviour with studies with 2k variables as well but not for studies with 1k variables or less. Seems 1k is the sweet spot. Any ideas where I should be looking at or is this limitation in NADA?

**Comment by mah0001** [comment]
This could be related to your PHP timeout settings, the default timeout value is 30 seconds. For studies with 4k variables, you will need to increase the timeout value. Check your php.ini for "max_execution_time" and increase the value to 120.

**Comment by t3chbg** [comment]
Thanks Mehmood - I also increased the memory_limit - That seemed to do the trick.
