### ISSUE TITLE
pdf generation error

### ISSUE THREAD

**Issue by chandee77** [ihsn/nada#28]
Hi Mehmood,
when run pdf generator  "......./index.php/admin/pdf_generator/setup/401" 
I get error "HTTP ERROR 500" 
my environment is IIS 8.5 , mbstring enabled..
How can I track down I couldn't find any error msg in php or iis log's
where can I get nada error logs...

**Comment by mah0001** [comment]
You can try to enable error logging to see the error. Edit the `application/config/config.php`, and set the `log_threshold` to 1. See below:

```
$config['log_threshold'] = 1;
```

and then try to generate the PDF again and then look inside the logs folder in NADA to see if any errors are logged.

You can also edit the `index.php` file and around line 66, change the value for 'ENVIRONMENT' to `development` from `production`. This should print the error messages in the browser.

```
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
```

Please post the actual error messages and then we can work on resolving it.

**Comment by chandee77** [comment]
Thanks  Mr.Mehmood... actually I figured out the issue it was write permission of temp folder
