### ISSUE TITLE
Unable to upload studies 

### ISSUE THREAD

**Issue by Trjegul84** [ihsn/nada#29]
Hello everyone! 
Please I need some help with NADA 5.0.6 configuration. It was installed in Linux Centos 7 with mysql 5.7 and php 7.4, everything was fine until the upload files in add studies was tested.  I can't find the right folder where the study files are uploaded,   **datafiles**, **imports** and **files** folders have 777 permissions but nothing works. Other attachment upload actions like citation files and **bulk import ddi** works but not this one. Please help me to find the path or missing configuration. This is the image of the error.

![Screenshot_20210222_120904](https://user-images.githubusercontent.com/72577339/108745544-35a39300-7509-11eb-852f-53509f71951f.png)
  

thanks.

**Comment by mah0001** [comment]
The files are uploaded to the 'datafiles/tmp' folder before they are processed. When you set WRITE permissions did you set them recursively? Can you try running this command:

```
sudo chmod -R 777 datafiles
```

Once you can confirm this solves the issue, you should change the permissions to 775:
```
sudo chmod -R 775 datafiles
```

**Comment by Trjegul84** [comment]
Thanks for the answer but they already have the recursive permissions applied. 

![Screenshot_20210222_144533](https://user-images.githubusercontent.com/72577339/108761545-fb43f100-751c-11eb-9f8f-eed96a63a84a.png)

In the configuration section, the folder does not highlight the check mark with green. Is this a problem?

![Screenshot_20210222_144725](https://user-images.githubusercontent.com/72577339/108762091-a9e83180-751d-11eb-8451-0d18e5c3eb76.png)

**Comment by mah0001** [comment]
Everything looks right. We can try a quick call [teams/webex/zoom] to debug. My email is mah0001@gmail.com.
