### ISSUE TITLE
issue when editing metadata

### ISSUE THREAD

**Issue by fredvandykjhu** [ihsn/nada#35]
Dear NADA team, One issue:
I'm using v5.2.

When editing metadata in the Site admin:   the _description of scope_ is populating the _abstract_ field and  _description of scope_ is empty.     The data looks correct on the front end, and in the XML file:

In XML (located: C:\inetpub\wwwroot\nada\datafiles\central\[guid]\ ):
  stdyDscr>
    stdyInfo>
      abstract>  (appears correctly on front end, Identification.Abstract)
		(Does not appear in metadata on admin page)

  stdyDscr>
    stdyInfo>
      notes>  (appears correctly on front end, Scope.Notes)
	(Appears in metadata “Overview.Abstract” on admin page)

It could be an error on my part, but I'm having trouble figuring out what is causing it.    
Thanks!
Fred

**Comment by mah0001** [comment]
Thank you for reporting this. The abstract and scope fields were not mapped correctly in the template. To fix the issue, use this file ([survey_form_template.json.zip](https://github.com/ihsn/nada/files/8655344/survey_form_template.json.zip)). Unzip and copy it to your nada folder (`/application/metadata_editor_templates/`) to replacing the existing `survey_form_template.json` file.

.

**Comment by fredvandykjhu** [comment]
Great, I just updated the file, and it looks good now.  Thanks!
