### ISSUE TITLE
Variables groups ?

### ISSUE THREAD

**Issue by Alhrath** [ihsn/nada#5]
In nada4 under "data description", you had the option to select "variable groups". I can't find this option in nada5. Do you plan to implement this feature ? Or am I missing something  ?

**Comment by mah0001** [comment]
It is not implemented yet for NADA5, we will add it.

**Comment by mah0001** [comment]
@Alhrath - Variable groups are now in the 'develop' branch. To try:

1) Add the table:

```
CREATE TABLE `variable_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sid` int(11) DEFAULT NULL,
  `vgid` varchar(45) DEFAULT NULL,
  `variables` varchar(5000) DEFAULT NULL,
  `variable_groups` varchar(500) DEFAULT NULL,
  `group_type` varchar(45) DEFAULT NULL,
  `label` varchar(255) DEFAULT NULL,
  `universe` varchar(255) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `txt` varchar(500) DEFAULT NULL,
  `definition` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```

2) Import a new DDI or go to study edit page and run DDI Refresh. To see the variable groups, go to the study information page and open the 'Data Description' tab.

<img width="1142" alt="Screen Shot 2019-05-17 at 10 15 03 PM" src="https://user-images.githubusercontent.com/223824/57964349-29d17880-7902-11e9-939b-80bbf1133959.png">
