### ISSUE TITLE
mysql UPDATE TABLE `survey`

### ISSUE THREAD

**Issue by Alhrath** [ihsn/nada#7]
Hi,
During the mysql database upgrade from 4.4 to 5, the following line : 

_install/nada5-upgrade-mysql.sql:56_
```
UPDATE TABLE `surveys` set type='survey';
```
produce an error. I corrected it this way : 
```
UPDATE `surveys` set `type`='survey'; 
```
Is this correct ?

**Comment by mah0001** [comment]
Yes, looks right. 'type' is a mysql reserved word, so should be enclosed in backticks, will update the upgrade script.

thanks
