### ISSUE TITLE
mysql and InnoDB version

### ISSUE THREAD

**Issue by Alhrath** [ihsn/nada#8]
Hello,
Mysql 5.6 use InnoDB Antelope by default, therefore I got some warnings during mysql nada5 update : 
```
InnoDB: ROW_FORMAT=DYNAMIC requires innodb_file_format > Antelope.
InnoDB: assuming ROW_FORMAT=COMPACT.

```
Do you thing it is safe to ignore these warnings or do you thing dynamic row format is mandatory and we should deploy Barracuda on our servers ? (which would represent quite some additional work).

**Comment by mah0001** [comment]
You can ignore the warnings, It should work fine.

**Comment by Alhrath** [comment]
Thanks
