### ISSUE TITLE
Data Deposit Page not loading

### ISSUE THREAD

**Issue by NickNck** [ihsn/nada#80]
The data deposit page in site administration is not loading. I am getting the error HTTP ERROR 500

**Comment by mah0001** [comment]
@NickNck - Data deposit is not installed by default with NADA. Please follow these steps to install the database tables and enable data deposit:

- Run the SQL from the file `install/schema.dd.mysql.sql` on your NADA database to create data deposit tables
- To enable data deposit, edit the configuration file `application/config/datadeposit.php`.
- Change the setting `enable_datadeposit` to `TRUE`:

```
  $config['datadeposit']['enable_datadeposit'] = TRUE; ```
```
    
- Save the file.
- Open web browser and navigate to <your-nada-catalog>/index.php/datadeposit.

Here is a link to the documentation - https://ihsn.github.io/nada-documentation/admin-guide/web-ui/data-deposit.html

If you still get 500 errors after installation, try this to see the actual error message:
- edit 'index.php' file and on  line number 66, change the environment to `development' from `production`:

```
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
```

- Make sure to change the value back to `production` once you have resolved the issue.
