### ISSUE TITLE
Data deposit - XML tag filled in automatically when the form is empty

### ISSUE THREAD

**Issue by ceracine** [ihsn/nada#91]
Hi,

When I fill in the form of the Data deposit, If I leave some fields empty, the corresponding XML tags will be filled in automatically.
Two fields are concerned :

- version date
- collection mode

![XML_version_date_empty](https://github.com/ihsn/nada/assets/109536024/11e43d31-550d-476e-938b-e92f5477e883)

![XML_collection_mode_empty](https://github.com/ihsn/nada/assets/109536024/427dbf35-9cee-406b-91aa-98df5dae2e37)

Is it normal ?

Thank you very much

**Comment by ceracine** [comment]
This issue is on the latest version : Nada 5.3

**Comment by mah0001** [comment]
Fixed
